apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dengalo-app.fullname" . }}-web
  labels:
    {{- include "dengalo-app.labels" . | nindent 4 }}
    apptype: web
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dengalo-app.selectorLabels" . | nindent 6 }}
      apptype: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "dengalo-app.selectorLabels" . | nindent 8 }}
        apptype: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.webimage.repository }}:{{ .Values.webimage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webimage.pullPolicy }}
