apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appService.name }}
  labels:
    {{- include "dengalo-app.labels" . | nindent 4 }}-app
spec:
  type: {{ .Values.appService.type }}
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.port }}
      name: liberty
  selector:
    {{- include "dengalo-app.selectorLabels" . | nindent 4 }}
    apptype: app

